sonar.sources=espacios-publicos-backend/src,espacios-publicos-frontend/src,.github,scripts
sonar.tests=espacios-publicos-backend/tests
sonar.test.inclusions=espacios-publicos-backend/tests/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,espacios-publicos-backend/prisma/**
sonar.cpd.exclusions=espacios-publicos-backend/tests/**/*.test.ts
sonar.sourceEncoding=UTF-8
